/* Autogenerated by png2wx.pl on Sat Jun 30 23:29:03 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_osm;
extern wxBitmap *_img_osm_pi;
extern wxBitmap *_img_download;
extern wxBitmap *_img_start;

#endif /* ICONS_H */
