/* Autogenerated by png2wx.pl on Thu Jun 28 18:49:54 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_download;
extern wxBitmap *_img_osm_pi;
extern wxBitmap *_img_osm;

#endif /* ICONS_H */
